service_name: "user"

server:
    host: "127.0.0.1"
    port: 3003

mysql:
    host: "127.0.0.1"
    username: "mysql"
    password: "mysql"
    port: 3306
    db_name: "user"

auth:
  host: "127.0.0.1"
  port: 3002

email:
  host: "127.0.0.1"
  port: 3004