service_name: "auth"

server:
    host: "127.0.0.1"
    port: 8082

mysql:
    host: "127.0.0.1"
    username: root
    password: "docker@!3A"
    port: 3306
    db_name: "auth"

redis:
    host: "127.0.0.1"
    username: "redis"
    password:
    port: 6379
    db: 0

user_service:
    host: "127.0.0.1"
    port: 8083

email_service:
    host: "127.0.0.1"
    port: 8084