service_name: "order"

server:
    host: "127.0.0.1"
    port: 3000

mysql:
    host: "127.0.0.1"
    username: "mysql"
    password: "mysql"
    port: 3306
    db_name: "order"

payment_service:
    host: "127.0.0.1"
    port: 3001