service_name: "product"

server:
    host: "127.0.0.1"
    port: 8085

mysql:
    host: "127.0.0.1"
    username: "root"
    password: "docker@!3A"
    port: 3306
    db_name: "book"

order_service:
    host: "127.0.0.1"
    port: 8080